language: cpp
install:
    - '[ -d /tmp/freeipmi_built/lib ] || wget -O /tmp/freeipmi-1.2.1.tar.gz http://ftp.gnu.org/gnu/freeipmi/freeipmi-1.2.1.tar.gz'
    - '[ -d /tmp/freeipmi_built/lib ] || (cd /tmp; tar -xzvf freeipmi-1.2.1.tar.gz)'
    - '[ -d /tmp/freeipmi_built/lib ] || (cd /tmp/freeipmi-1.2.1/; ./configure --prefix=/tmp/freeipmi_built)'
    - '[ -d /tmp/freeipmi_built/lib ] || (cd /tmp/freeipmi-1.2.1/; make -j2 install)'
    - '[ -d /tmp/freeipmi_built/lib ]'
cache:
    directories:
        - /tmp/freeipmi_built
script:
    - export IPMILIB_PATHS="-I/tmp/freeipmi_built/include -L/tmp/freeipmi_built/lib"
    - make
    - (cd clientapi; python3 -m sysmgr)
    - export LD_LIBRARY_PATH="/tmp/freeipmi_built/lib"
    - ./sysmgr --version
compiler: gcc
addons:
    apt:
        packages:
            - libconfuse-dev
            - libgcrypt11-dev
            - libxml++2.6-dev
            - python3
            - python-tornado
            - libboost-dev
